services:
  postgres:
    image: postgres:16
    container_name: gridops-postgres

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    ports:
      - "${POSTGRES_PORT}:5432"

    volumes:
      - gridops_postgres_data:/var/lib/postgresql/data

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"
        ]
      interval: 5s
      timeout: 5s
      retries: 5


  mlflow:
    image: gridops-api:dev
    container_name: gridops-mlflow

    command:
      [
        "mlflow",
        "server",
        "--backend-store-uri",
        "sqlite:////mlflow/mlflow.db",
        "--default-artifact-root",
        "file:///mlflow/mlartifacts",
        "--host",
        "0.0.0.0",
        "--port",
        "5000",
        "--allowed-hosts",
        "mlflow:5000,localhost:*,127.0.0.1:*"
      ]

    ports:
      - "5000:5000"

    volumes:
      - ./mlflow.db:/mlflow/mlflow.db
      - ./mlartifacts:/mlflow/mlartifacts

    healthcheck:
      test:
        [
          "CMD",
          "python",
          "-c",
          "import urllib.request; urllib.request.urlopen('http://localhost:5000/health').read()"
        ]
      interval: 5s
      timeout: 5s
      retries: 10


  api:
    build:
      context: .
    image: gridops-api:dev
    container_name: gridops-api

    env_file:
      - .env

    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      AWS_PROFILE: gridops-dev
      AWS_REGION: us-east-1
      AWS_CONFIG_FILE: /root/.aws/config

    volumes:
      - type: bind
        source: "C:/Users/ykkad/.aws"
        target: /root/.aws

    ports:
      - "8000:8000"

    depends_on:
      postgres:
        condition: service_healthy

        
  ingestion:
    image: gridops-api:dev
    container_name: gridops-ingestion

    env_file:
      - .env

    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      AWS_PROFILE: gridops-dev
      AWS_REGION: us-east-1
      AWS_CONFIG_FILE: /root/.aws/config

    volumes:
      - type: bind
        source: "C:/Users/ykkad/.aws"
        target: /root/.aws

    depends_on:
      postgres:
        condition: service_healthy

    command:
      [
        "python",
        "-u",
        "scripts/run_eia_scheduler.py"
      ]

    restart: unless-stopped

volumes:
  gridops_postgres_data: